name: Docs
on:
  push:
    tags: ["*-element.*"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
    - run: yarn install
    - run: yarn docs
    - name: Build and deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .jsdoc/@vector-im/matrix-bot-sdk/${{ github.ref_name }}
